In [ ]:
!pip install xgboost
!pip install category-encoders
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from category_encoders import OrdinalEncoder


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 3.1 MB/s eta 0:00:00


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving women_clean_data.csv to women_clean_data (2).csv


In [ ]:
import pandas as pd
df = pd.read_csv('women_clean_data.csv')

In [ ]:
# Assuming X_train is your DataFrame
categorical_cols = ["Black", "Result", "TimeControl", "Moves"]

In [ ]:
# Initialize the OrdinalEncoder
encoder = OrdinalEncoder(cols=categorical_cols)

In [ ]:
# Fit and transform the encoder on your training data
X_train = encoder.fit_transform(X_train)

In [ ]:
# Transform your test data using the same encoder
X_test = encoder.transform(X_test)

In [ ]:
# Now you can create the DMatrix
dtrain = xgb.DMatrix(X_train[:56], label=y_train) # Ensure X_train and y_train have the same number of rows - slicing X_train to have 56 rows like y_train
dtest = xgb.DMatrix(X_test)   # Ensure X_test and y_test have the same number of rows - removing y_test since it has 0 rows

In [ ]:
# Print the shapes of your data and labels to double-check
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(9736, 4) (56, 1)
(2435, 4) (0, 1)


In [ ]:
# Set parameters for XGBoost
params = {
    'objective': 'multi:softmax',  # Softmax for multi-class classification
    'num_class': 3,                # We have 3 classes (1 for white win, 0 for black win, 2 for draw)
    'max_depth': 4,                # Reducing max depth to 4
    'eta': 0.1,                    # Reducing learning rate
    'seed': 42                     # Random seed
}

In [ ]:
# Train the XGBoost model with fewer rounds
num_rounds = 50  # Reducing the number of boosting rounds
xgb_model = xgb.train(params, dtrain, num_rounds)

In [ ]:
# Make predictions using the XGBoost model
y_pred_xgb = xgb_model.predict(dtest)

In [ ]:
# Check data types
print(f"Data type of y_test: {type(y_test)}")
print(f"Data type of y_pred_xgb: {type(y_pred_xgb)}")

Data type of y_test: <class 'pandas.core.series.Series'>
Data type of y_pred_xgb: <class 'numpy.ndarray'>


In [ ]:
# Check for mixed types in y_test
print(f"Unique values in y_test: {set([type(item) for item in y_test])}")

Unique values in y_test: {<class 'str'>}


In [ ]:
# Check unique values in y_pred_xgb
print(f"Unique predicted values: {np.unique(y_pred_xgb)}")

Unique predicted values: ['0']


In [ ]:
# Convert y_pred_xgb to have consistent data type (e.g., string)
y_pred_xgb = y_pred_xgb.astype(str)

In [ ]:
# Convert y_test to have consistent data type (e.g., string)
y_test = y_test.astype(str)

In [ ]:
# Ensure both y_test and y_pred_xgb are of type string
# This is important for comparing predicted and actual labels in classification tasks
y_test = y_test.astype(str)

In [ ]:

# Evaluate the XGBoost model
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:
# Display results
print(f"XGBoost Accuracy: {accuracy_xgb}")
print("XGBoost Confusion Matrix:")
print(conf_matrix_xgb)
print("XGBoost Classification Report:")
print(class_report_xgb)

XGBoost Accuracy: 0.0
XGBoost Confusion Matrix:
[[ 0  0  0 ...  0  0  0]
 [17  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]]
XGBoost Classification Report:
                                  precision    recall  f1-score   support

                               0       0.00      0.00      0.00       0.0
                               ?       0.00      0.00      0.00      17.0
                   Abasov, Nijat       0.00      0.00      0.00       1.0
          Abdukhakimov, Akbarali       0.00      0.00      0.00       1.0
             Abdumalik, Zhansaya       0.00      0.00      0.00      25.0
          Abdusattorov, Nodirbek       0.00      0.00      0.00       1.0
               Abrahamyan, Tatev       0.00      0.00      0.00       2.0
             Adewumi, Tanitoluwa       0.00      0.00      0.00       1.0
                   Ahmad, Khagan       0.00      0.00      0.00       1.0
              Al Mukhain